nodeLinker: node-modules

packageExtensions:
  "recyclerlistview@*":
    patchedDependencies:
      "recyclerlistview@4.2.1": "./patches/fix-VirtualRenderer.patch"

# yarnPath: .yarn/releases/yarn-3.6.4.cjs
